In [3]:
! pip3 install numpy



[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip


In [168]:
import numpy as np

2.

In [15]:
arr=np.zeros((4,6))
print(arr)
arr1=np.full((4,6),35)
print(arr1)
arr3=np.arange(101,131,2)
print(arr3)
print(arr3.size)
arr4=np.linspace(0,3,7)
print(arr4)
arr5=np.eye(5)*10
print(arr5)
arr6=np.full((4,4),35)+np.eye(4)*65

print(arr6)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[35 35 35 35 35 35]
 [35 35 35 35 35 35]
 [35 35 35 35 35 35]
 [35 35 35 35 35 35]]
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
15
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]
[[100.  35.  35.  35.]
 [ 35. 100.  35.  35.]
 [ 35.  35. 100.  35.]
 [ 35.  35.  35. 100.]]


5.

In [47]:
totals=np.array([245,310,178,392,140,265,199,155,288,132])
arr1=totals[totals>250]
print(arr1)
arr3=totals[totals>180] & totals[totals<250]
print(arr3)
# arr4=totals[totals<150] | totals[totals>180]
#print(arr4)
print(arr3.size)
arr4=(totals>250)
arr5=(totals>250).sum()
print(arr5/arr4.size)
arr6=np.where(totals<150)
print(arr6)
arr7=((totals<250).sum())
print(arr7)


[310 392 265 288]
[245  50 136   1 131   0]
6
0.4
(array([4, 9]),)
6


6.

In [ ]:
marks = np.array([40, 55, 62, 88, 95, 33, 71, 58])
x=marks+0.15
print(x)
arr3=(x[x<=100])
arr4=x[x<10]
print(arr4.size)
print(arr3)
arr5=marks[marks<40]
arr6=x[x<40]
print(arr5.size)
print(arr6.size)
arr7=(marks/95)*100
print(np.round(arr7,1))
print(0.15*marks.size)




[40.15 55.15 62.15 88.15 95.15 33.15 71.15 58.15]
0
[40.15 55.15 62.15 88.15 95.15 33.15 71.15 58.15]
1
1
[ 42.1  57.9  65.3  92.6 100.   34.7  74.7  61.1]
1.2


7.

In [ ]:
marks = np.array([72, 45, 88, 95, 30, 67, 91, 54, 78, 39])
avg=marks.mean()
print(avg)
mid=np.median(marks)
print(mid)
print(np.where(marks==95))
print(np.where(marks==30))
print(np.partition(marks,-2)[-2])
print(np.std(marks))
a=marks[marks<=21.77]
print(a.size)
a1=marks[marks<95]

print(a1.mean())



65.9
69.5
(array([3]),)
(array([4]),)
91
21.773607877428123
0
62.666666666666664


8.

In [115]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40],
                  [30, 48, 62, 70]])
                  
                  
arr=np.mean(marks,axis=0)
print(arr)
print(marks.size)
a=np.min(arr)
print(np.where(arr==a))
print(np.max(marks,axis=0))
a2=np.where(marks>60)
a3=np.std(marks)
print(np.where(marks==a3))
print(a2)
ar=marks[:,1:2]
arm=ar.min()
print(arm)

[66.  64.2 69.8 71.2]
20
(array([1]),)
[ 95  92  98 100]
(array([], dtype=int64), array([], dtype=int64))
(array([0, 0, 0, 1, 2, 2, 2, 2, 3, 3, 4, 4]), array([0, 1, 3, 2, 0, 1, 2, 3, 0, 1, 2, 3]))
30


9

In [218]:
x=np.random.seed(42)

participants = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
z=np.random.randint(101,111,3)
print(z)

y=np.random.randint(60,101,10)
print(y)
print(y[y>80])
x=np.random.rand(4,3)
x=np.random.randint(0,101,(4,3))
print(x)
np.random.shuffle(participants)
print(participants[0:4])
x=np.random.randint(1,7,20)
y=x[x==6]
print(y.size)





[107 104 108]
[80 98 78 82 70 70 83 95 99 83]
[98 82 83 95 99 83]
[[91 59 79]
 [14 61 61]
 [46 61 50]
 [54 63  2]]
[109 108 106 104]
3


10.

In [233]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40]])
  
grace = np.array([5, 0, 8, 3])
weightage = np.array([1.2, 1.0, 1.1, 1.0])
arr=marks+grace  
print(arr)
arr1=np.where(arr>100,100,arr)  
print(arr1) 
arr2=marks * weightage
print(arr2) 
arr4=np.mean(arr,axis=0)        
print(arr4)
arr5=arr-arr4
print(arr5)
arr6=arr[0][::1]+5
print(arr6)
arr7=arr[1][::1]+0
arr8=arr[2][::1]+2
arr9=arr[3][::1]+0

print(arr7)
print(arr8)
print(arr9)


[[ 77  85  68  94]
 [ 50  30 106  58]
 [ 93  66  82 103]
 [100  92  63  43]]
[[ 77  85  68  94]
 [ 50  30 100  58]
 [ 93  66  82 100]
 [100  92  63  43]]
[[ 86.4  85.   66.   91. ]
 [ 54.   30.  107.8  55. ]
 [105.6  66.   81.4 100. ]
 [114.   92.   60.5  40. ]]
[80.   68.25 79.75 74.5 ]
[[ -3.    16.75 -11.75  19.5 ]
 [-30.   -38.25  26.25 -16.5 ]
 [ 13.    -2.25   2.25  28.5 ]
 [ 20.    23.75 -16.75 -31.5 ]]
[82 90 73 99]
[ 50  30 106  58]
[ 95  68  84 105]
[100  92  63  43]
